#!/usr/bin/env python3
"""
splat-pp.py — Splatoon 3 Plaza Post Printer
Converts a 320x120 B&W PNG into a complete Arduino sketch, compiles it,
and flashes it to a Teensy 4.0 emulating a Nintendo Switch Pro Controller.

Usage:
    python splat-pp.py <image.png> [--duration <ms>] [--template <file>]

Output approach — data-driven bytecode:
    Rather than emitting one function call per step (which overflows the
    Teensy 4.0's 512 KB ITCM code region for complex images), the tool
    encodes every move as a compact byte sequence stored in a PROGMEM array.
    A tiny interpreter loop (~30 lines of C) reads and executes each opcode
    at runtime. Machine-code footprint: ~200 bytes of code + N bytes of data,
    regardless of image complexity.

Bytecode format (each instruction is 1-3 bytes):
    OP_DRAW  0x00        -- press A (stamp current pixel)
    OP_UP    0x01 <n>    -- move cursor up n steps
    OP_DOWN  0x02 <n>    -- move cursor down n steps
    OP_LEFT  0x03 <n>    -- move cursor left n steps
    OP_RIGHT 0x04 <n>    -- move cursor right n steps

    n is a single byte (1-255). Moves >255 steps are split automatically.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("Missing dependencies. Run: pip install pillow numpy")
    sys.exit(1)

# ── Board configuration ───────────────────────────────────────────────────────
# USB type: nsgamepad = Nintendo Switch Gamepad (Hori controller emulation)
# This requires the NSGadget_Teensy patches installed by setup-nsgadget.sh
FQBN = "teensy:avr:teensy40:usb=nsgamepad"
MCU  = "TEENSY40"

# ── Paths (relative to this script) ──────────────────────────────────────────
SCRIPT_DIR = Path(__file__).parent
SKETCH_DIR = SCRIPT_DIR / "sketch"
BUILD_DIR  = SCRIPT_DIR / "build"

# ── Canvas constants ──────────────────────────────────────────────────────────
CANVAS_W = 320
CANVAS_H = 120

# ── Bytecode opcodes ──────────────────────────────────────────────────────────
OP_DRAW  = 0x00
OP_UP    = 0x01
OP_DOWN  = 0x02
OP_LEFT  = 0x03
OP_RIGHT = 0x04


def load_image(path: str) -> np.ndarray:
    """Load PNG, resize to 320x120 if needed, threshold to pure B&W.
    Returns boolean array: True = black pixel (draw), False = white."""
    img = Image.open(path).convert("L")
    if img.size != (CANVAS_W, CANVAS_H):
        print(f"  Resizing {img.size} -> ({CANVAS_W}, {CANVAS_H})")
        img = img.resize((CANVAS_W, CANVAS_H), Image.LANCZOS)
    return np.array(img) < 128


def plan_moves(black: np.ndarray) -> list:
    """Snake-scan: left->right on even rows, right->left on odd rows."""
    pixels = []
    for row in range(black.shape[0]):
        cols = np.where(black[row])[0]
        if len(cols) == 0:
            continue
        if row % 2 == 0:
            pixels.extend((int(c), row) for c in cols)
        else:
            pixels.extend((int(c), row) for c in reversed(cols))
    return pixels


def encode_bytecode(pixels: list) -> bytearray:
    """Encode pixel visit sequence into compact bytecode.
    Cursor starts at (0,0) matching runMacro()'s holdStick reset."""
    buf = bytearray()
    cx, cy = 0, 0

    def emit_move(opcode, steps):
        while steps > 0:
            n = min(steps, 255)
            buf.append(opcode)
            buf.append(n)
            steps -= n

    for tx, ty in pixels:
        dx = tx - cx
        dy = ty - cy
        if dy > 0:
            emit_move(OP_DOWN, dy)
        elif dy < 0:
            emit_move(OP_UP, -dy)
        if dx > 0:
            emit_move(OP_RIGHT, dx)
        elif dx < 0:
            emit_move(OP_LEFT, -dx)
        buf.append(OP_DRAW)
        cx, cy = tx, ty

    return buf


def count_actions(bytecode: bytearray) -> int:
    """Count total runtime calls the interpreter will make (for time estimate)."""
    total = 0
    i = 0
    while i < len(bytecode):
        op = bytecode[i]; i += 1
        if op == OP_DRAW:
            total += 1
        else:
            n = bytecode[i]; i += 1
            total += n
    return total


def format_progmem_array(data: bytearray, name: str) -> str:
    """Format bytes as a C PROGMEM array, 16 bytes per row."""
    rows = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        rows.append("  " + ", ".join(f"0x{b:02X}" for b in chunk))
    return (
        f"static const uint8_t {name}[] PROGMEM = {{\n"
        + ",\n".join(rows)
        + "\n};"
    )


DRAW_FUNCTION_TEMPLATE = """\
// Auto-generated by splat-pp.py
// Source  : {source}
// Pixels  : {pixel_count:,}
// Bytecode: {byte_count:,} bytes
// Duration: {duration}ms per action
// Est. time: {est_s:.0f}s ({est_min:.1f} min)
//
// The image is stored as a PROGMEM data array, not function calls.
// A small interpreter loop executes each opcode at runtime.
// This keeps compiled code size tiny regardless of image complexity.

#include <avr/pgmspace.h>

#define OP_DRAW  0x00
#define OP_UP    0x01
#define OP_DOWN  0x02
#define OP_LEFT  0x03
#define OP_RIGHT 0x04

{array}

void drawImage(unsigned int duration = 25) {{
  const uint32_t len = sizeof(imageData);
  for (uint32_t i = 0; i < len; ) {{
    uint8_t op = pgm_read_byte(&imageData[i++]);
    if (op == OP_DRAW) {{
      pressButton(BUTTON_A_INDEX, duration, duration);
    }} else {{
      uint8_t n = pgm_read_byte(&imageData[i++]);
      uint8_t dir;
      switch (op) {{
        case OP_UP:    dir = DPAD_UP;    break;
        case OP_DOWN:  dir = DPAD_DOWN;  break;
        case OP_LEFT:  dir = DPAD_LEFT;  break;
        case OP_RIGHT: dir = DPAD_RIGHT; break;
        default:       dir = DPAD_CENTERED; break;
      }}
      for (uint8_t j = 0; j < n; j++) setDPad(dir, duration);
    }}
  }}
}}
"""


def generate_draw_function(bytecode, pixel_count, duration, source, actions):
    est_s = (actions * duration * 2) / 1000
    return DRAW_FUNCTION_TEMPLATE.format(
        source=source,
        pixel_count=pixel_count,
        byte_count=len(bytecode),
        duration=duration,
        est_s=est_s,
        est_min=est_s / 60,
        array=format_progmem_array(bytecode, "imageData"),
    )


def generate_full_sketch(template_path: str, draw_function: str) -> str:
    """Read template and replace placeholder with generated drawImage function."""
    template = Path(template_path).read_text(encoding="utf-8")
    placeholder_start = "////////////////////////////////////////\n// PASTE THE drawImage FUNCTION BELOW //\n////////////////////////////////////////"
    placeholder_end = "////////////////////////////////////////"

    start_idx = template.find(placeholder_start)
    if start_idx == -1:
        raise ValueError(f"Could not find start marker in template: {template_path}")

    end_idx = template.find(placeholder_end, start_idx + len(placeholder_start))
    if end_idx == -1:
        raise ValueError(f"Could not find end marker in template: {template_path}")

    before = template[:start_idx + len(placeholder_start)]
    after = template[end_idx:]

    return before + "\n" + draw_function + "\n" + after


def compile_sketch(sketch_dir: Path) -> Path:
    """Compile the sketch with arduino-cli. Returns path to the hex file.

    The build directory is always wiped before compiling so arduino-cli's
    precompiled-header cache (build/pch/Arduino.h) is never stale.
    C++14/17 compatibility is handled by setup-nsgadget.sh patching
    IntervalTimer.h in the Teensy core directly.
    """
    print(f"\nCompiling {sketch_dir.name}...")

    # Always wipe the build dir before compiling.
    # arduino-cli caches a precompiled Arduino.h in build/pch/. If a prior
    # failed build left that cache behind, compiler flag changes (like the
    # C++17 override below) are silently ignored and the old errors repeat.
    if BUILD_DIR.exists():
        shutil.rmtree(BUILD_DIR)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        [
            "arduino-cli", "compile",
            "--fqbn", FQBN,
            "--build-path", str(BUILD_DIR),
            str(sketch_dir),
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        print("Compile failed:\n")
        print(result.stderr)
        sys.exit(1)

    # Print size line from stdout
    for line in result.stdout.splitlines():
        if "Sketch uses" in line or "Global variables" in line:
            print(f"  {line.strip()}")

    hex_file = BUILD_DIR / f"{sketch_dir.name}.ino.hex"
    if not hex_file.exists():
        print(f"Error: expected hex file not found: {hex_file}")
        sys.exit(1)

    print("  Compile successful.")
    return hex_file


def flash_teensy(hex_file: Path):
    """Prompt user then flash hex to Teensy."""
    print("\n─────────────────────────────────────────")
    print("  Ready to flash.")
    print("  Press the button on your Teensy, then")
    input("  press Enter here to flash... ")
    print("─────────────────────────────────────────")

    result = subprocess.run(
        [
            "teensy_loader_cli",
            f"--mcu={MCU}",
            "-w", "-v",
            str(hex_file),
        ],
        capture_output=True,
        text=True,
    )

    print(result.stdout)
    if result.returncode != 0:
        print("Flash failed:\n")
        print(result.stderr)
        sys.exit(1)


def parse_args():
    p = argparse.ArgumentParser(
        description="Convert a B&W PNG into a Splatoon Post Printer sketch, compile, and flash."
    )
    p.add_argument("image", help="Path to source PNG")
    p.add_argument("--duration", type=int, default=25,
                   help="ms per action (default 25, range 20-200)")
    p.add_argument("--template", default="sketch.txt",
                   help="Path to Arduino sketch template (default: sketch.txt)")
    return p.parse_args()


def main():
    args = parse_args()

    if not (20 <= args.duration <= 200):
        print(f"Error: --duration must be 20-200 ms (got {args.duration})")
        sys.exit(1)

    img_path = Path(args.image)
    if not img_path.exists():
        print(f"Error: file not found: {img_path}")
        sys.exit(1)

    template_path = Path(args.template)
    if not template_path.exists():
        print(f"Error: template not found: {template_path}")
        sys.exit(1)

    # ── Convert ───────────────────────────────────────────────────────────────
    print(f"Loading image: {img_path}")
    black = load_image(str(img_path))
    pixel_count = int(black.sum())
    print(f"  Black pixels: {pixel_count:,} / {CANVAS_W * CANVAS_H:,}")

    print("Planning snake-scan move sequence...")
    pixels = plan_moves(black)
    print(f"  Draw operations: {len(pixels):,}")

    print("Encoding bytecode...")
    bytecode = encode_bytecode(pixels)
    actions = count_actions(bytecode)
    est_s = (actions * args.duration * 2) / 1000
    print(f"  Bytecode size : {len(bytecode):,} bytes")
    print(f"  Est. draw time: {est_s:.0f}s ({est_s/60:.1f} min)")

    # ── Generate sketch ───────────────────────────────────────────────────────
    print("Merging with template...")
    draw_function = generate_draw_function(
        bytecode, pixel_count, args.duration, img_path.name, actions
    )
    full_sketch = generate_full_sketch(str(template_path), draw_function)

    base_name = img_path.stem
    sketch_dir = SKETCH_DIR / base_name
    sketch_dir.mkdir(parents=True, exist_ok=True)
    out_path = sketch_dir / f"{base_name}.ino"
    out_path.write_text(full_sketch, encoding="utf-8")
    print(f"  Written to: {out_path}")

    # ── Compile ───────────────────────────────────────────────────────────────
    hex_file = compile_sketch(sketch_dir)

    # ── Flash ─────────────────────────────────────────────────────────────────
    flash_teensy(hex_file)

    # ── Clean up build dir ────────────────────────────────────────────────────
    print("\nCleaning up build directory...")
    shutil.rmtree(BUILD_DIR)

    print("\nDone! Connect your Teensy to the Switch and head to the plaza post printer!")

if __name__ == "__main__":
    main()
